import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "../../context/userContext";
import { CartProvider } from "../../context/panierContext";


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Ada Delice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
           <body className={inter.className}>

    <UserProvider>
          <CartProvider>
            {children}
            <Toaster position="top-right" />
          </CartProvider>
        </UserProvider>
      

      </body>
    </html>
  );
}
